### PR TITLE
Autoload helpers in composer.json

### PR DESCRIPTION
**Pull request by ghost**
Do not load helpers in middleware, but use Composer instead

### CODE REVIEW

**Comment by saleem-hadad** [comment]
thank you @Arcesilas 
can you explain why?

**Comment by ghost** [comment]
Best practice.

**Comment by ghost** [comment]
Actually, there is no real consensus about best practices to load custom helpers.

I've found some answers which use `composer.json` and some which load the file in the ServiceProvider.

I consider this is best practice, because when using Composer, we delegate autoloading. I think it's a good thing to let Composer load files for us.

Anyway, it's a very subjective opinion and you are completly free to no agree. Loading the helpers file from within the Service Provider works, and that's the most important, in the end.

**Comment by saleem-hadad** [comment]
I really appreciate your work and contributions. 
If that's the only difference I'd prefer to stick to the old method as long as it does its job :D

**Pull request closed without merging**
